### PR TITLE
Add new example impedance adjustable with frequency

### PR DESCRIPTION
**Pull request by akilamarimuthu**
Added new example named AD5940_Impedance adjustable with frequency.

### CODE REVIEW

**Review by JayrPerez — APPROVED** [review]
Please add explanation for each change and their purpose/reason for changing next time.
Thanks!

**Comment by markramos0822** [comment]
Hi @akilamarimuthu 
Can you document how is this different from the original example code?

regards,
Mark

**Comment by akilamarimuthu** [comment]
Hi @markramos0822 ,
  In this example, AppImpCheckFreq() function is added to enable updating of AFE parameters for each excitation frequency if frequency sweep is enabled.

**Comment by markramos0822** [comment]
Noted @akilamarimuthu 
@JayrPerez do you know if this can be added to the commit comments now? Or do we need to reject to pull request first to do that?

**Comment by JayrPerez** [comment]
@markramos0822 about the commit comments, do you mean the commit message? If yes, changing the commit message is a bit too complicated and may affect the file history. It might be better to reject the pull request and just approve a new pull request with a documented commit message.

**Comment by markramos0822** [comment]
Thanks @JayrPerez 
@akilamarimuthu, I will disapprove this request for now. Please update the commit message first and then submit a new pull request. This is to make sure that the commits are documented well to avoid asking the same question in the future.

**Pull request closed without merging**
